import type { Question, JobType } from "./types";

export const questions: Question[] = [
  {
    id: 1,
    scenario: "チームでプロジェクトを始めるとき、あなたは？",
    options: [
      { id: "1a", text: "みんなを集めてキックオフを仕切る", scores: { E: 3, J: 1 } },
      { id: "1b", text: "まず一人で全体像を整理してから共有する", scores: { I: 3, J: 1 } },
      { id: "1c", text: "雑談しながらアイデアを出し合いたい", scores: { E: 2, P: 2 } },
      { id: "1d", text: "資料を読み込んで静かに準備を進める", scores: { I: 2, S: 2 } },
    ],
  },
  {
    id: 2,
    scenario: "締め切りが迫っているとき、あなたの行動は？",
    options: [
      { id: "2a", text: "計画通りに淡々とこなす", scores: { J: 3, S: 1 } },
      { id: "2b", text: "ギリギリで爆発的な集中力を発揮する", scores: { P: 3, N: 1 } },
      { id: "2c", text: "優先順位を論理的に再整理する", scores: { T: 3, J: 1 } },
      { id: "2d", text: "周りに声をかけて協力体制をつくる", scores: { F: 2, E: 2 } },
    ],
  },
  {
    id: 3,
    scenario: "意見が対立したとき、あなたはどうする？",
    options: [
      { id: "3a", text: "データや根拠を示して論理的に説得する", scores: { T: 3, S: 1 } },
      { id: "3b", text: "相手の気持ちを汲んで落としどころを探る", scores: { F: 3, E: 1 } },
      { id: "3c", text: "第三の選択肢をクリエイティブに提案する", scores: { N: 3, P: 1 } },
      { id: "3d", text: "一度引いて、冷静に考え直す時間をとる", scores: { I: 2, T: 2 } },
    ],
  },
  {
    id: 4,
    scenario: "新しいサービスのアイデアを考えるなら？",
    options: [
      { id: "4a", text: "市場データを分析して確実なニーズを見つける", scores: { S: 3, T: 1 } },
      { id: "4b", text: "未来の理想像から逆算して構想する", scores: { N: 3, T: 1 } },
      { id: "4c", text: "身近な人の困りごとからヒントを得る", scores: { F: 2, S: 2 } },
      { id: "4d", text: "異業種の成功事例を組み合わせてみる", scores: { N: 2, P: 2 } },
    ],
  },
  {
    id: 5,
    scenario: "休日の過ごし方で理想に近いのは？",
    options: [
      { id: "5a", text: "友達とワイワイ出かける", scores: { E: 3, F: 1 } },
      { id: "5b", text: "一人でカフェで読書や勉強", scores: { I: 3, S: 1 } },
      { id: "5c", text: "新しい場所やイベントを開拓する", scores: { E: 2, N: 2 } },
      { id: "5d", text: "家で好きなことにとことん没頭する", scores: { I: 2, P: 2 } },
    ],
  },
  {
    id: 6,
    scenario: "仕事で一番やりがいを感じる瞬間は？",
    options: [
      { id: "6a", text: "チームで大きな成果を出したとき", scores: { E: 2, F: 2 } },
      { id: "6b", text: "難しい問題を自力で解決したとき", scores: { I: 2, T: 2 } },
      { id: "6c", text: "自分のアイデアが形になったとき", scores: { N: 2, P: 2 } },
      { id: "6d", text: "計画通りに物事が進んだとき", scores: { S: 2, J: 2 } },
    ],
  },
  {
    id: 7,
    scenario: "上司から「自由にやっていい」と言われたら？",
    options: [
      { id: "7a", text: "わくわくして色々試したくなる", scores: { P: 3, N: 1 } },
      { id: "7b", text: "まずゴールと基準を確認したい", scores: { J: 3, S: 1 } },
      { id: "7c", text: "チームメンバーと方向性を相談する", scores: { E: 2, F: 2 } },
      { id: "7d", text: "過去の成功パターンを参考に進める", scores: { S: 2, J: 2 } },
    ],
  },
  {
    id: 8,
    scenario: "プレゼンで一番大事にしたいことは？",
    options: [
      { id: "8a", text: "論理的な構成とエビデンス", scores: { T: 3, S: 1 } },
      { id: "8b", text: "聞き手の感情に訴えるストーリー", scores: { F: 3, N: 1 } },
      { id: "8c", text: "インパクトのあるビジュアルと演出", scores: { N: 2, E: 2 } },
      { id: "8d", text: "実現可能性を示す具体的な計画", scores: { S: 2, J: 2 } },
    ],
  },
  {
    id: 9,
    scenario: "失敗したとき、最初に考えることは？",
    options: [
      { id: "9a", text: "原因を分析して再発防止策を立てる", scores: { T: 3, J: 1 } },
      { id: "9b", text: "周りへの影響を確認してフォローする", scores: { F: 3, E: 1 } },
      { id: "9c", text: "失敗から新しい可能性を見出す", scores: { N: 3, P: 1 } },
      { id: "9d", text: "事実を整理して次に同じミスをしない", scores: { S: 2, T: 2 } },
    ],
  },
  {
    id: 10,
    scenario: "理想の働き方に近いのは？",
    options: [
      { id: "10a", text: "多くの人と関わりながらリードする", scores: { E: 3, J: 1 } },
      { id: "10b", text: "専門性を深めてプロフェッショナルになる", scores: { I: 2, T: 2 } },
      { id: "10c", text: "新しいことに次々チャレンジする", scores: { N: 2, P: 2 } },
      { id: "10d", text: "安定した環境で着実に成長する", scores: { S: 2, J: 2 } },
    ],
  },
  {
    id: 11,
    scenario: "グループワークでの自分の役割は？",
    options: [
      { id: "11a", text: "議論をリードして結論を導く", scores: { E: 2, T: 2 } },
      { id: "11b", text: "メンバーの意見を引き出してまとめる", scores: { E: 1, F: 3 } },
      { id: "11c", text: "独自の視点でアイデアを投げ込む", scores: { N: 2, I: 2 } },
      { id: "11d", text: "情報を整理して資料にまとめる", scores: { S: 2, I: 2 } },
    ],
  },
  {
    id: 12,
    scenario: "10年後のキャリアで重視したいことは？",
    options: [
      { id: "12a", text: "社会にインパクトを与える仕事をしている", scores: { N: 2, E: 2 } },
      { id: "12b", text: "専門分野で誰にも負けないスキルを持つ", scores: { T: 2, I: 2 } },
      { id: "12c", text: "信頼できる仲間と良いチームを築いている", scores: { F: 2, E: 2 } },
      { id: "12d", text: "ワークライフバランスを保ちながら安定している", scores: { S: 2, J: 2 } },
    ],
  },
];

export const jobTypes: JobType[] = [
  {
    mbti: "ENTJ",
    jobName: "経営コンサルタント",
    title: "戦略の覇王",
    emoji: "👑",
    color: "#7C3AED",
    soulAnalysis: "生まれながらのリーダー。複雑な課題を俯瞰し、最短ルートで成果を出す。周囲を巻き込む推進力が最大の武器。",
    strengths: "戦略立案・意思決定・組織マネジメント",
    weakness: "完璧主義で人の感情を見落としがち",
    recommendedField: "コンサル / 経営企画 / 事業開発",
    bestPartner: "ISFP",
    bestPartnerReason: "繊細な感性が、あなたの戦略に人間味を加えてくれる最高の相棒。",
    negativeLoop: "全部自分でやろうとして疲弊 → 周囲との溝 → 孤立感",
    statusBase: { breakthrough: 90, coordination: 55, logic: 85, creativity: 70, empathy: 40 },
  },
  {
    mbti: "ENTP",
    jobName: "新規事業プランナー",
    title: "閃きの魔術師",
    emoji: "⚡",
    color: "#F59E0B",
    soulAnalysis: "アイデアの泉が枯れることはない。既存の枠を壊して新しい価値を生み出す天才。議論と刺激が何よりの栄養。",
    strengths: "発想力・ディベート・問題発見力",
    weakness: "飽き性で最後までやり切るのが苦手",
    recommendedField: "スタートアップ / 企画 / マーケティング",
    bestPartner: "ISFJ",
    bestPartnerReason: "あなたのアイデアを丁寧に形にしてくれる、縁の下の力持ち。",
    negativeLoop: "興味が移り続ける → 中途半端 → 実績が積めない焦り",
    statusBase: { breakthrough: 75, coordination: 50, logic: 80, creativity: 95, empathy: 45 },
  },
  {
    mbti: "ENFJ",
    jobName: "人事・組織開発",
    title: "導きの聖者",
    emoji: "🌟",
    color: "#EC4899",
    soulAnalysis: "人の可能性を見抜き、成長を導く天性のメンター。組織のビジョンを言葉にし、人を動かすカリスマ性を持つ。",
    strengths: "コミュニケーション・育成・ビジョン共有",
    weakness: "他人に尽くしすぎて自分を後回しにする",
    recommendedField: "人事 / 教育 / NPO / 広報",
    bestPartner: "ISTP",
    bestPartnerReason: "冷静な分析力で、あなたの情熱にリアリティを加えてくれる。",
    negativeLoop: "みんなに好かれたい → 八方美人 → 本音が言えなくなる",
    statusBase: { breakthrough: 65, coordination: 90, logic: 50, creativity: 60, empathy: 95 },
  },
  {
    mbti: "ENFP",
    jobName: "クリエイティブディレクター",
    title: "情熱の冒険家",
    emoji: "🔥",
    color: "#F97316",
    soulAnalysis: "好奇心と情熱のかたまり。人を巻き込む力は天下一品。新しい可能性を見つけ、世界を広げていく開拓者。",
    strengths: "共感力・企画力・ネットワーキング",
    weakness: "感情の波が大きく、ルーティンが苦手",
    recommendedField: "広告 / メディア / イベント企画",
    bestPartner: "ISTJ",
    bestPartnerReason: "堅実な実行力で、あなたの夢を地に足のついた計画に変えてくれる。",
    negativeLoop: "やりたいこと多すぎ → 手を広げすぎ → どれも中途半端",
    statusBase: { breakthrough: 70, coordination: 75, logic: 45, creativity: 90, empathy: 85 },
  },
  {
    mbti: "INTJ",
    jobName: "データサイエンティスト",
    title: "深淵の策士",
    emoji: "🧠",
    color: "#6366F1",
    soulAnalysis: "独自の世界観と戦略眼で未来を見通す孤高の知略家。複雑なシステムの本質を見抜く力は誰にも負けない。",
    strengths: "戦略思考・分析力・長期計画",
    weakness: "他人に任せられず孤立しやすい",
    recommendedField: "IT / 研究開発 / 金融 / 戦略コンサル",
    bestPartner: "ESFP",
    bestPartnerReason: "明るい行動力が、あなたの戦略を楽しく実行に移してくれる。",
    negativeLoop: "理想が高すぎ → 現実とのギャップ → 行動できなくなる",
    statusBase: { breakthrough: 60, coordination: 35, logic: 95, creativity: 85, empathy: 30 },
  },
  {
    mbti: "INTP",
    jobName: "プロダクトエンジニア",
    title: "知識の探求者",
    emoji: "🔬",
    color: "#06B6D4",
    soulAnalysis: "知的好奇心の塊。複雑な問題を分解し、本質に迫る分析力は他の追随を許さない。静かなる天才肌。",
    strengths: "論理的思考・技術力・問題解決",
    weakness: "コミュニケーションが受け身になりがち",
    recommendedField: "エンジニア / 研究職 / アナリスト",
    bestPartner: "ESFJ",
    bestPartnerReason: "社交力と実行力で、あなたのアイデアを世に送り出してくれる。",
    negativeLoop: "考えすぎ → 動けない → 周囲に置いていかれる不安",
    statusBase: { breakthrough: 45, coordination: 30, logic: 95, creativity: 90, empathy: 35 },
  },
  {
    mbti: "INFJ",
    jobName: "UXデザイナー",
    title: "静寂の予言者",
    emoji: "🔮",
    color: "#8B5CF6",
    soulAnalysis: "深い洞察力と共感力で人の心を読み解く。理想を追い求め、意味のある仕事に全力を注ぐ完璧主義者。",
    strengths: "洞察力・共感力・ビジョン構築",
    weakness: "理想と現実のギャップに苦しみやすい",
    recommendedField: "デザイン / 心理 / 教育 / ライター",
    bestPartner: "ESTP",
    bestPartnerReason: "圧倒的な行動力が、あなたのビジョンをスピーディに実現してくれる。",
    negativeLoop: "理想に執着 → 妥協できない → 前に進めない",
    statusBase: { breakthrough: 40, coordination: 60, logic: 65, creativity: 85, empathy: 90 },
  },
  {
    mbti: "INFP",
    jobName: "コンテンツクリエイター",
    title: "夢想の吟遊詩人",
    emoji: "🎨",
    color: "#A855F7",
    soulAnalysis: "豊かな内面世界と創造性を持つアーティスト気質。自分の価値観に忠実で、意味のある仕事を求め続ける。",
    strengths: "創造力・文章力・共感力",
    weakness: "批判に弱く、自己評価が低くなりがち",
    recommendedField: "クリエイティブ / ライター / カウンセラー",
    bestPartner: "ESTJ",
    bestPartnerReason: "強力な実行力と組織力で、あなたの作品を世に届ける最強のプロデューサー。",
    negativeLoop: "自分らしさに固執 → 選択肢が狭まる → 就活が進まない",
    statusBase: { breakthrough: 35, coordination: 45, logic: 50, creativity: 95, empathy: 90 },
  },
  {
    mbti: "ESTJ",
    jobName: "プロジェクトマネージャー",
    title: "鉄壁の司令官",
    emoji: "🛡️",
    color: "#059669",
    soulAnalysis: "責任感と実行力の鬼。組織を動かし、確実に成果を出す。ルールと秩序を重んじ、チームの柱となる。",
    strengths: "実行力・管理能力・責任感",
    weakness: "柔軟性に欠け、変化への対応が遅れがち",
    recommendedField: "メーカー / 金融 / 公務員 / PM",
    bestPartner: "INFP",
    bestPartnerReason: "柔らかい発想力が、あなたの組織に創造性と温かさを加えてくれる。",
    negativeLoop: "ルールに固執 → 新しいやり方を拒否 → 時代に取り残される不安",
    statusBase: { breakthrough: 80, coordination: 70, logic: 75, creativity: 35, empathy: 45 },
  },
  {
    mbti: "ESFJ",
    jobName: "営業・カスタマーサクセス",
    title: "絆の守護者",
    emoji: "💎",
    color: "#0EA5E9",
    soulAnalysis: "チームの潤滑油であり太陽。人間関係を大切にし、周囲をサポートすることで組織全体を輝かせる。",
    strengths: "対人スキル・チームワーク・ホスピタリティ",
    weakness: "人の評価を気にしすぎてストレスを溜めやすい",
    recommendedField: "営業 / 接客 / 医療 / 教育",
    bestPartner: "INTP",
    bestPartnerReason: "深い知識と独自の視点が、あなたの対人力にプロの深みを加えてくれる。",
    negativeLoop: "周りに合わせすぎ → 自分の軸がブレる → 何がしたいかわからなくなる",
    statusBase: { breakthrough: 55, coordination: 95, logic: 40, creativity: 40, empathy: 90 },
  },
  {
    mbti: "ESTP",
    jobName: "起業家・セールス",
    title: "疾風の切り込み隊長",
    emoji: "⚔️",
    color: "#EF4444",
    soulAnalysis: "行動力と瞬発力の化身。チャンスを逃さない嗅覚と、現場を動かすカリスマ性で道を切り拓く。",
    strengths: "行動力・交渉力・危機対応力",
    weakness: "長期計画が苦手で飽きっぽい",
    recommendedField: "営業 / 起業 / スポーツ / メディア",
    bestPartner: "INFJ",
    bestPartnerReason: "深い洞察力が、あなたの行動に戦略的な意味を与えてくれる。",
    negativeLoop: "とりあえず動く → 方向性が定まらない → 同じところをぐるぐる",
    statusBase: { breakthrough: 95, coordination: 60, logic: 55, creativity: 50, empathy: 50 },
  },
  {
    mbti: "ESFP",
    jobName: "イベントプロデューサー",
    title: "祝祭のエンターテイナー",
    emoji: "🎪",
    color: "#F43F5E",
    soulAnalysis: "場を盛り上げる天才。ポジティブなエネルギーで周囲を巻き込み、人を笑顔にすることが最大の喜び。",
    strengths: "表現力・社交性・臨機応変さ",
    weakness: "計画性が弱く、目の前の楽しさに流されやすい",
    recommendedField: "エンタメ / 広告 / 飲食 / ブライダル",
    bestPartner: "INTJ",
    bestPartnerReason: "緻密な戦略が、あなたのエンタメ力を最大限に活かすシナリオを描いてくれる。",
    negativeLoop: "楽しそうな方に流される → 軸がない → 企業選びが進まない",
    statusBase: { breakthrough: 70, coordination: 80, logic: 30, creativity: 75, empathy: 85 },
  },
  {
    mbti: "ISTJ",
    jobName: "経理・財務アナリスト",
    title: "不動の守り手",
    emoji: "🏰",
    color: "#475569",
    soulAnalysis: "信頼と誠実の象徴。正確さと責任感で組織の土台を支える。コツコツ積み上げる力は誰にも真似できない。",
    strengths: "正確性・責任感・継続力",
    weakness: "新しいやり方への抵抗感が強い",
    recommendedField: "経理 / 法務 / 品質管理 / 公務員",
    bestPartner: "ENFP",
    bestPartnerReason: "あふれる情熱と新しい視点が、あなたの安定した基盤に刺激と彩りを加えてくれる。",
    negativeLoop: "安定志向すぎ → チャレンジを避ける → 可能性を狭める",
    statusBase: { breakthrough: 50, coordination: 55, logic: 85, creativity: 25, empathy: 45 },
  },
  {
    mbti: "ISFJ",
    jobName: "総務・バックオフィス",
    title: "癒しの盾使い",
    emoji: "🍀",
    color: "#10B981",
    soulAnalysis: "縁の下の力持ち。誰よりも細やかな気配りで組織を支え、人の役に立つことに喜びを感じる。",
    strengths: "気配り・丁寧さ・サポート力",
    weakness: "自己主張が苦手で頼まれると断れない",
    recommendedField: "事務 / 医療 / 福祉 / カスタマーサポート",
    bestPartner: "ENTP",
    bestPartnerReason: "大胆なアイデアと行動力が、あなたの丁寧さと組み合わさって最強のチームに。",
    negativeLoop: "断れない → 仕事が増える → 自分のやりたいことが見えなくなる",
    statusBase: { breakthrough: 35, coordination: 85, logic: 55, creativity: 30, empathy: 95 },
  },
  {
    mbti: "ISTP",
    jobName: "ITエンジニア",
    title: "沈黙の技巧師",
    emoji: "🔧",
    color: "#64748B",
    soulAnalysis: "冷静沈着な職人気質。手を動かして問題を解決する実践力と、独立心の強さが武器。",
    strengths: "技術力・問題解決力・冷静さ",
    weakness: "チームワークよりも単独行動を好みすぎる",
    recommendedField: "エンジニア / 技術職 / 設計 / 職人",
    bestPartner: "ENFJ",
    bestPartnerReason: "温かいリーダーシップが、あなたの技術力を最大限チームに活かしてくれる。",
    negativeLoop: "一人で抱え込む → 情報共有不足 → チームから浮く",
    statusBase: { breakthrough: 55, coordination: 30, logic: 90, creativity: 60, empathy: 25 },
  },
  {
    mbti: "ISFP",
    jobName: "デザイナー・アーティスト",
    title: "静謐の芸術家",
    emoji: "🌸",
    color: "#D946EF",
    soulAnalysis: "感性豊かで穏やかな芸術家気質。自分のペースで美しいものを生み出し、周囲に癒しを与える。",
    strengths: "美的センス・柔軟性・共感力",
    weakness: "競争的な環境でストレスを感じやすい",
    recommendedField: "デザイン / アート / 美容 / 自然関連",
    bestPartner: "ENTJ",
    bestPartnerReason: "力強いリーダーシップが、あなたの繊細な才能を大きな舞台へ押し上げてくれる。",
    negativeLoop: "競争が苦手 → 就活に消極的 → 自信をなくす",
    statusBase: { breakthrough: 30, coordination: 50, logic: 40, creativity: 90, empathy: 85 },
  },
];
